{% set name = "django-timezone-field" %}
{% set version = "7.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_timezone_field-{{ version }}.tar.gz
  sha256: def846f9e7200b7b8f2a28fcce2b78fb2d470f6a9f272b07c4e014f6ba4c6d2e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - django >=3.2,<6.1
    - backports.zoneinfo <0.3.0,>=0.2.1
    - pytz
    # - Django <6.0,>=3.2
    # - Django <6.1,>=3.2

test:
  commands:
    - python -c "import django; from django.conf import settings; settings.configure(DEBUG=True,USE_DEPRECATED_PYTZ=[' VERSION < (4, 0))']); django.setup(); import timezone_field"
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mfogel/django-timezone-field/
  summary: A Django app providing DB, form, and REST framework fields for zoneinfo and pytz timezone objects.
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
