{% set name = "django-timezone-field" %}
{% set version = "4.1.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cffac62452d060e365938aa9c9f7b72d70d8b26b9c60243bce227b35abd1b9df

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - django >=2.2
    - python >=3.5
    - pytz
    - djangorestframework >=3.0.0

test:
  imports:
    - timezone_field
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/mfogel/django-timezone-field/
  summary: A Django app providing database and form fields for pytz timezone objects.
  license: BSD-2-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
    - hadim
